name: Dev Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Deploy to my EC2 instance
        env:
          NAME: SUSANTO
          AGE: 25
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SOURCE: "./*"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ""
          EXCLUDE: "/node_modules/"

          SCRIPT_AFTER : |

            # export MONGODB_DB_NAME=${{ secrets.MONGODB_DB_NAME }} &&
            # export MONGODB_CLUSTER_ADDRESS=${{ secrets.MONGODB_CLUSTER_ADDRESS }} &&
            # export MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} &&
            # export MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} &&
            # export PORT=${{ secrets.PORT }} &&

            echo "NAME = $NAME"
            echo "AGE = $AGE"
            npm install
            npm run build
            pm2 restart nest-server
