name: Dev Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: List
        run: cd dist && ls

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SOURCE: "./*"
          REMOTE_HOST: "ec2-54-83-113-247.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: ""
          SCRIPT_AFTER: |
            export MONGODB_CLUSTER_ADDRESS=cluster0.dkejpa2.mongodb.net
            export MONGODB_USERNAME=susanto
            export MONGODB_PASSWORD=GhL0v1sJhdTKZlW2
            export MONGODB_DB_NAME=studentdb
            export PORT=3000
